---
# Ansible playbook for a virtualboxubuntu1604 server.
#
# @author Jeff Geerling (2014).

- hosts: virtualboxubuntu1604
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.nfs
    - geerlingguy.git
    - geerlingguy.docker
    - gantsign.intellij
    - gantsign.java
    - gantsign.maven
    - cmprescott.chrome
  tasks:
    - name: install base packages 
      apt:
        name:
        - wget
        - curl
        - vim
        - htop
        - tmux
